"""Automatic component filenames shared by loaders and Settings (no GPU imports)."""

RESOURCE_DEFAULTS = {
    'clip_aura': 'clip_aura.safetensors',
    'clip_ernie_enhancer': 'ernie-image-prompt-enhancer.safetensors',
    'clip_g': 'clip_g.safetensors',
    'clip_gemma': 'gemma_2_2b_fp16.safetensors',
    'clip_gemma2_it': 'gemma_2_2b_it_bf16.safetensors',
    'clip_gemma2_it_elm': 'gemma_2_2b_it_elm_fp8_scaled.safetensors',
    'clip_gemma3': 'gemma_3_4b_it_bf16.safetensors',
    'clip_gemma3_12b': 'gemma-3-12b-it-Q4_0.gguf',
    'clip_gemma4_12b': 'gemma4-12b-with-proj-ltx-2.5-comfy-int8-convrot.safetensors',
    'clip_jina': 'jina_clip_v2_bf16.safetensors',
    'clip_l': 'clip_l.safetensors',
    'clip_llama': 'llama_q2.gguf',
    'clip_llava': 'llava_llama3_fp8_scaled.safetensors',
    'clip_ltx23_text_proj': 'ltx-2.3_text_projection_bf16.safetensors',
    'clip_ltx2_dev': 'ltx-2-19b-embeddings_connector_dev_bf16.safetensors',
    'clip_ltx2_distilled': 'ltx-2-19b-embeddings_connector_distill_bf16.safetensors',
    'clip_ministral3': 'ministral-3-3b.safetensors',
    'clip_mistral3': 'mistral_3_small_flux2_fp8.safetensors',
    'clip_oldt5': 't5xxl_old_fp32-q4_0.gguf',
    'clip_qwen25': 'qwen_2.5_vl_7b_fp8_scaled.safetensors',
    'clip_qwen3_06b': 'qwen_3_06b_base.safetensors',
    'clip_qwen3_4b': 'Qwen3-4B-Q4_K_M.gguf',
    'clip_qwen3_8b': 'Qwen3-8B-Q8_0.gguf',
    'clip_qwen3vl_32b': 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors',
    'clip_qwen3vl_4b': 'qwen3vl_4b_bf16.safetensors',
    'clip_qwen3vl_4b_scaled': 'qwen3vl_4b_fp8_scaled.safetensors',
    'clip_qwen3vl_8b': 'qwen3vl_8b_fp8_scaled.safetensors',
    'clip_qwen3vl_8b_scaled': 'qwen3vl_8b_fp8_scaled.safetensors',
    'clip_t5': 't5-v1_1-xxl-encoder-Q3_K_S.gguf',
    'clip_umt5': 'umt5_xxl_fp8_e4m3fn_scaled.safetensors',
    'clip_vision': 'clip_vision_h_fp8_e4m3fn.safetensors',
    'vae_auraflow': 'auraflow_vae_fp32.safetensors',
    'vae_flux': 'ae.safetensors',
    'vae_flux2': 'flux2-vae.safetensors',
    'vae_hunyuan_video': 'hunyuan_video_vae_bf16.safetensors',
    'vae_ltxv': 'LTX-Video-0.9.6-VAE-BF16.safetensors',
    'vae_ltxv23_audio': 'LTX23_audio_vae_bf16.safetensors',
    'vae_ltxv23_video': 'LTX23_video_vae_bf16.safetensors',
    'vae_ltxv25_audio': 'ltx-2.5-audio-vae-bf16.safetensors',
    'vae_ltxv25_video': 'ltx-2.5-video-vae-bf16.safetensors',
    'vae_ltxv2_audio': 'LTX2_audio_vae_bf16.safetensors',
    'vae_ltxv2_video': 'LTX2_video_vae_bf16.safetensors',
    'vae_lumina2': 'lumina2_vae_fp32.safetensors',
    'vae_mage_flow': 'mage_flow_vae_bf16.safetensors',
    'vae_minimax_h3_audio': 'minimax_h3_audio_vae_fp32.safetensors',
    'vae_minimax_h3_video': 'minimax_h3_video_vae_fp16.safetensors',
    'vae_pixart': 'pixart_vae_fp16.safetensors',
    'vae_qwen_image': 'qwen_image_vae.safetensors',
    'vae_sd': 'sd15_vae.safetensors',
    'vae_sd3': 'sd3_vae.safetensors',
    'vae_sdxl': 'sdxl_vae.safetensors',
    'vae_wan': 'wan_2.1_vae.safetensors',
    'vae_wan_22': 'wan2.2_vae.safetensors',
}

def resource_name(key, values):
    return values.get(key) or RESOURCE_DEFAULTS.get(key)

RESOURCE_LABELS = {
    "clip_aura": "AuraFlow encoder", "clip_g": "CLIP G (SDXL / SD3 / HiDream)",
    "clip_l": "CLIP L (SD / SDXL / Flux / SD3 / HiDream / Hunyuan)",
    "clip_t5": "T5 (Flux / HiDream / SD3 / PixArt / LTX)",
    "clip_gemma": "Lumina 2 Gemma", "clip_gemma2_it_elm": "PixelDiT Gemma 2",
    "clip_gemma3": "NewBieImage Gemma 3", "clip_jina": "NewBieImage Jina",
    "clip_ernie_enhancer": "Ernie prompt enhancer", "clip_ministral3": "ErnieImage Ministral",
    "clip_mistral3": "Flux 2 Mistral", "clip_llama": "HiDream Llama",
    "clip_llava": "Hunyuan Video LLaVA", "clip_oldt5": "Cosmos Predict 2 T5",
    "clip_qwen25": "Qwen Image Qwen 2.5 VL", "clip_qwen3_06b": "Anima Qwen 3 0.6B",
    "clip_qwen3_4b": "Flux 2 Klein 4B / Z Image Qwen 3",
    "clip_qwen3_8b": "Flux 2 Klein 9B Qwen 3 8B",
    "clip_qwen3vl_4b": "Mage-Flow Qwen 3 VL", "clip_qwen3vl_4b_scaled": "Krea 2 Qwen 3 VL",
    "clip_qwen3vl_8b": "Ideogram 4 Qwen 3 VL", "clip_qwen3vl_8b_scaled": "Boogu Image Qwen 3 VL",
    "clip_qwen3vl_32b": "MiniMax H3 official Qwen 3 VL",
    "clip_gemma3_12b": "LTX 2 / 2.3 Gemma 3", "clip_gemma4_12b": "LTX 2.5 Gemma 4",
    "clip_ltx23_text_proj": "LTX 2.3 text projection", "clip_ltx2_dev": "LTX 2 Dev connector",
    "clip_ltx2_distilled": "LTX 2 Distilled connector", "clip_umt5": "Wan UMT5",
    "clip_vision": "Wan image-to-video vision encoder",
    "vae_sdxl": "SDXL / Pony / Illustrious VAE", "vae_sd": "SD 1.5 VAE",
    "vae_qwen_image": "Qwen Image / Anima VAE", "vae_flux": "Flux VAE",
    "vae_lumina2": "Lumina 2 / Z Image VAE", "vae_sd3": "SD3 / HiDream VAE",
}
